### ISSUE TITLE
Rewrite in Haskell

### ISSUE THREAD

**Issue by tibbon** [danchoi/vmail#189]
I might be trolling you. Or not.

**Comment by danchoi** [comment]
Are you Haskelling?

**Comment by tibbon** [comment]
Attempting to Learn Me a Haskell. I need to break past some initial issues
that I'm having, mostly in breaking out of more traditional software
patterns (input/output and mutability mostly).

I'd like to get to the point where I can write a simple API with Haskell,
but that seems a long way off.

**Comment by danchoi** [comment]
Get the Graham Hutton Haskell book too -- the parsing chapter in that book is very helpful & the pure function chapters in Hutton are a better intro to the power of pure Haskell functions than the corresponding material in LYAH.

Also, when you get to Applicative Functors in LYAH, study that carefully. You may be skeptical at first  how they can even be useful. But I use them everywhere. They are as important as monads. Real World Haskell book also has good practical Applicative Functor examples in the chapter on Parsec.

**Comment by danchoi** [comment]
Let's continue the conversation off thread. This is the wrong place.
