### ISSUE TITLE
Vmail fails with a Net::IMAP::BadResponseError

### ISSUE THREAD

**Issue by aftnix** [danchoi/vmail#192]
Vmail spits this error message and stops...

/home/aftnix/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/imap.rb:1143:in `get_tagged_response': Unknown command nq3mb150502939pdb (Net::IMAP::BadResponseError)
        from /home/aftnix/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/imap.rb:1195:in `block in send_command'
        from /home/aftnix/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
        from /home/aftnix/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/imap.rb:1177:in `send_command'
        from /home/aftnix/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/imap.rb:526:in `block in list'
        from /home/aftnix/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
        from /home/aftnix/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/imap.rb:525:in `list'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/lib/vmail/imap_client.rb:166:in `list_mailboxes'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/lib/vmail/imap_client.rb:196:in `mailboxes'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/lib/vmail/imap_client.rb:184:in `block (2 levels) in mailbox_aliases'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/lib/vmail/imap_client.rb:183:in `each'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/lib/vmail/imap_client.rb:183:in `block in mailbox_aliases'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/lib/vmail/imap_client.rb:182:in `each'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/lib/vmail/imap_client.rb:182:in `mailbox_aliases'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/lib/vmail/imap_client.rb:92:in `select_mailbox'
        from /home/aftnix/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/drb/drb.rb:1083:in `method_missing'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/lib/vmail.rb:79:in `start'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/gems/vmail-2.9.3/bin/vmail:14:in `<top (required)>'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/bin/vmail:23:in `load'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/bin/vmail:23:in `<main>'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
        from /home/aftnix/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

**Comment by notalex** [comment]
You are getting a bad response from Gmail. This can happen when your gmail account is configured to allow only Oauth2 applications to connect.

Try the following and check vmail again:

Go to myaccount.google.com -> "connected apps & sites", and turn "Allow less secure apps" to "ON" (near the bottom of the page).

If it works, please let me know so that I can close this ticket.

**Comment by aftnix** [comment]
Thanks a lot. It worked like a charm.

**Comment by danchoi** [comment]
Thanks for being a great maintainer @notalex

**Comment by notalex** [comment]
Thanks @danchoi, I hope to do more in future.

**Comment by wturrell** [comment]
My recommended solution, 5 years later:

https://myaccount.google.com/security > App Passwords (under *Signing into Google*)
Create a new one, you then use this instead of your normal password in `.vmailrc`
Start vmail and it should load fine.

Every time you create a new app password, you have to enter your main password, and it also sends you an email confirming one has been created, and you can see when it was last used.

**Comment by MikeCraig418** [comment]
> My recommended solution, 5 years later:
> 
> https://myaccount.google.com/security > App Passwords (under _Signing into Google_)
> Create a new one, you then use this instead of your normal password in `.vmailrc`
> Start vmail and it should load fine.
> 
> Every time you create a new app password, you have to enter your main password, and it also sends you an email confirming one has been created, and you can see when it was last used.

Awesome. This worked perfectly.
