### ISSUE TITLE
Remove dependence on Versionomy

### ISSUE THREAD

**Issue by MaciekChudek** [danchoi/vmail#194]
Currently neither versionomy, nor one of it's dependencies, blockenspiel, are in either the official Arch repos or the AUR (Arch User Repos). This makes vmail a serious pain to install on Arch, at least for those commited to Arch's packaging system.

I'm keen to maintain a vmail AUR package, to make vmail more accessible to Arch users, but don't especially want to have to maintain versionomy and blockenspiel packages too. It looks like currently versionomy is only used once, to check that the ruby version is >= 1.9.0, in vmail.rb. Can we just do this check by hand and ditch versionomy? Happy to submit a pull request to this effect.

**Comment by notalex** [comment]
@MaciekChudek, we recommend the rubygems package manger for installing Vmail. It makes it easier for us to maintain the dependencies. 

However, we can remove versionomy. I don't see it adding any value in the way it is being used now.

**Comment by MaciekChudek** [comment]
Great, thanks.

There are some pretty compelling reasons to stick with a single package management scheme, especially pacman under Arch. Upgrading, dependency tracking, uninstalling, migrating, etc., all become far easier and less likely to break things. But more importantly, by ditching versionomy it'll be possible for Arch users to go from zero to fully iinstalled vmail with a single command (or maybe two if they're fussy). Everyone loves convenience :-)
