### ISSUE TITLE
cannot delete email

### ISSUE THREAD

**Issue by hoangngan82** [danchoi/vmail#198]
Hi,
I delete my email in vmail but it is not deleted on server. Anytime I rerun vmail, I get all those deleted email again. Please help.
Thanks,
Ngan

**Comment by notalex** [comment]
@hoangngan82, I hope that the issue is resolved. If not, please see this [related issue](https://github.com/danchoi/vmail/issues/155).

**Comment by hoangngan82** [comment]
Hi, 

First, I would like to thank you all for your very cool software. 

I can delete emails now. The reason was that when I ran 
  vmail -g
the following error occur

Selecting [Gmail]/["Sent Mail"]
/usr/lib/ruby/2.3.0/net/imap.rb:1196:in `get_tagged_response':  Unknown Mailbox: [Gmail]/["Sent Mail"] (Failure) (Net::IMAP::NoResponseError)
        from /usr/lib/ruby/2.3.0/net/imap.rb:1250:in `block in send_command'
        from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /usr/lib/ruby/2.3.0/net/imap.rb:1232:in `send_command'
        from /usr/lib/ruby/2.3.0/net/imap.rb:454:in `block in select'
        from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /usr/lib/ruby/2.3.0/net/imap.rb:452:in `select'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail/contacts_extractor.rb:27:in `block in extract'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail/contacts_extractor.rb:17:in `open'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail/contacts_extractor.rb:23:in `extract'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail/options.rb:79:in `block (2 levels) in parse'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail/options.rb:78:in `open'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail/options.rb:78:in `block in parse'
        from /usr/lib/ruby/2.3.0/optparse.rb:1061:in `initialize'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail/options.rb:22:in `new'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail/options.rb:22:in `parse'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail/options.rb:18:in `initialize'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail.rb:44:in `new'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail.rb:44:in `options'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail.rb:48:in `config'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/lib/vmail.rb:21:in `start'
        from /home/hoangngan/.gem/ruby/2.3.0/gems/vmail-2.9.5/bin/vmail:14:in `<top (required)>'
        from /home/hoangngan/.gem/ruby/2.3.0/bin/vmail:23:in `load'
        from /home/hoangngan/.gem/ruby/2.3.0/bin/vmail:23:in `<main>'

In order to temporarily fixed it, I modified */path/to/lib/vmail/defaults.rb* by
changing ['Sent Mail'] to 'Sent Mail' (removing square brackets). This is of
course is not consistent with the rest of *defaults.rb* file but it makes 
  vmail -g
work. However, it screwed up *delete* command. When I changed *defaults.rb* to
its original version, deleting works flawlessly.

Thanks, 
Ngan

On Sun, Jan 24, 2016 at 11:20 PM, Alex <notifications@github.com> wrote:

> from: Alex <notifications@github.com>
> date: Sun, Jan 24 11:20 PM -08:00 2016
> to: danchoi/vmail <vmail@noreply.github.com>
> cc: Ngan Nguyen <zhoangngan@gmail.com>
> reply-to: danchoi/vmail <reply@reply.github.com>
> subject: Re: [vmail] cannot delete email (#198)
> 
> @hoangngan82, I hope that the issue is resolved. If not, please see this [related issue](https://github.com/danchoi/vmail/issues/155). 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/danchoi/vmail/issues/198#issuecomment-174424450

--
Hoang-Ngan Nguyen
