### ISSUE TITLE
Vmail not compatible with latest version of Vim.

### ISSUE THREAD

**Issue by TheGrandmother** [danchoi/vmail#204]
I'm running `vim` version `7.4.1819` and apparently the `--servername` option has been dropped :/
Although my `gvim` version is just `7.4.273` and it works fine.
Or maybe I have  haven't compiled `vim` correctly :/

**Comment by notalex** [comment]
I have the vim version `7.4.1689` and it does support `--servername`. I don't believe that `vim` would remove this option, that too in a minor version. Please try compiling it manually with the **+clientserver** flag.

**Known issues**: Some linux distros and OSx package vim without the `+clientserver` flag. Check #173 for more details.

**Comment by TheGrandmother** [comment]
Thanks!
You are correct it did not have the `clientserver` flag enabled.
