### ISSUE TITLE
Make -clientserver build optional

### ISSUE THREAD

**Issue by danchoi** [danchoi/vmail#206]
@notalex How hard would it be to make the requirement for building Vim with `-clientserver` optional?

While I'm glad you put in that feature, it has made installing Vmail rather more complicated than it perhaps should be for the majority who don't necessarily need that feature.

**Comment by notalex** [comment]
It is easily doable. I will get a PR in soon.

**Comment by danchoi** [comment]
Thank you @notalex

**Comment by notalex** [comment]
Fixed in a new [commit](https://github.com/danchoi/vmail/commit/cebcf23f0617eeae20bd370d4effdfc927ebbff7) on master. Published the new changes to rubygems.
