### ISSUE TITLE
VMAIL_ERROR: NoMethodError when updating

### ISSUE THREAD

**Issue by msravi** [danchoi/vmail#209]
Hi,

When I do an update using ",u", I get the following error:
```
Checking for new messages. Please wait...VMAIL_ERROR: NoMethodError

undefined method ‘has_clientserver?‘ for #<Vmail::ImapClient:0x007f396d41ff50>
[Library/Ruby/Gems/2.0.0/gems/vmail-2.9.8/lib/vmail/imap_client.rb:233:in ‘check_for_new_messages‘
[Library/Ruby/Gems/2.0.0/gems/vmail-2.9.8/lib/vmail/imap_client.rb:250:in ‘update‘
[System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/drb/drb.rb:1588:in ‘perform_without_block‘
[System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/drb/drb.rb:1548:in ‘perform‘
[System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/drb/drb.rb:1626:in ‘block (2 levels) in main_loop‘
[System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/drb/drb.rb:1622:in ‘loop‘
[System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/drb/drb.rb:1622:in ‘block in main_loop‘
```
The vmail.log file has the following relevant contents:
```
D, [2017-03-29T12:11:06.753978 #43223] DEBUG -- : Getting mailbox status
D, [2017-03-29T12:11:06.754032 #43223] DEBUG -- : Getting highest message id
D, [2017-03-29T12:11:07.843372 #43223] DEBUG -- : Highest seqno: 26189
D, [2017-03-29T12:11:07.843567 #43223] DEBUG -- : Search #update_query
D, [2017-03-29T12:11:08.154866 #43223] DEBUG -- : - got seqnos: [26188, 26189]
D, [2017-03-29T12:11:08.154986 #43223] DEBUG -- : - getting seqnos > 26188
D, [2017-03-29T12:11:08.155050 #43223] DEBUG -- : - setting max_seqno to 26189
D, [2017-03-29T12:11:08.155103 #43223] DEBUG -- : - new uids found: [26189]
D, [2017-03-29T12:14:28.774845 #43223] DEBUG -- : Closing connection
```
I'm using vmail v2.9.8 on OS X El Capitan (10.11.6)

Any hints on resolving this?
Thanks!

**Comment by msravi** [comment]
I was able to get this to work with the following:
```
git clone https://github.com/danchoi/vmail.git 
cd vmail 
git checkout habpy
ruby -Ilib bin/vmail 
```
which was posted in another issue. Looks like the habpy branch needs to be checked out for this to work properly...

**Comment by PedroLopes** [comment]
## reproducing the error
@msravi : I am running into the same error:
```
Checking for new messages. Please wait...VMAIL_ERROR: NoMethodError
undefined method `has_clientserver?' for #<Vmail::ImapClient:0x00007fa47c8ca988>
/Users/pedro/.rvm/gems/ruby-2.4.2/gems/vmail-2.9.8/lib/vmail/imap_client.rb:233:in `check_for_new_messages'
/Users/pedro/.rvm/gems/ruby-2.4.2/gems/vmail-2.9.8/lib/vmail/imap_client.rb:250:in `update'
... etc
```

## possible fix? 
1. If I comment out the call for "has_clientserver?" it works. Which leaves me to think it is related to that. In fact, re-adding the def of ``def has_clientserver?``and ``def vim`` from ``vmail.rb`` to ``imap_client.rb`` makes the whole thing work again. 
2. If the ``habpy`` version from gihub works better, perhaps promote that one to the gem? 

## system specs
vmail version: 2.9.8 (from gem)
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jan 13 2016 15:37:28
mac osx 

## last but not least
Thanks for this great tool.

**Comment by marskar** [comment]
Hi @PedroLopes,
I made a pull request (https://github.com/danchoi/vmail/pull/212) based on your solution.

I too am really grateful for such an awesome tool.
Thanks @danchoi, @notalex et al.!

**Comment by notalex** [comment]
The PR #212 has been merged and deployed to rubygems. Shall we close this issue?
