### ISSUE TITLE
Additional password insertion methods

### ISSUE THREAD

**Issue by towc** [danchoi/vmail#214]
The last comment on the last issue about this was in 2015 (https://github.com/danchoi/vmail/issues/188), so I thought it might be worth making a new one.

What I'd love is for it to ask you for the password at startup, and remember it until you explicitly log out, or restart the laptop.

I wouldn't want it as an env variable either (although it might be nice to have the option anyway), as it shows up in your history and remains on your screen after you quit the program. And just to reiterate, storing it as plain text is very inconvenient for a lot of people, and most encryption methods are going to be just as bad.

**Comment by notalex** [comment]
As I understand, we need a feature which allows Vmail to retain session even after closing the vmail window. It might be possible. We will have to continue this discussion in the original thread.

P.S. One could send vmail into background using (Ctrl-v Ctrl-z).
