### ISSUE TITLE
Not attaching

### ISSUE THREAD

**Issue by tom-adsfund** [danchoi/vmail#219]
The email client I always wanted!

Unfortunately when I use "attach:" nothing seems to attach. The lines disappear, but nothing is attached.

**Comment by tom-adsfund** [comment]
The problem is that the files are relative to the ~/.vmail/default folder, and using ~/... doesn't work.

**Comment by notalex** [comment]
I hope this issue is resolved.

**Comment by tom-adsfund** [comment]
@notalex I just use full paths, like /home/tom/myfile.txt
