### ISSUE TITLE
Google initially blocking access to account

### ISSUE THREAD

**Issue by sdondley** [danchoi/vmail#221]
I just downloaded vmail but had a problem with Google blocking access to it (spoiler alert: I got it working).

After setting up my config file, the message I got from vmail was `invalid credentials` with a scary trace following that. That wasn't very encouraging, especially after I double/triple/quadruple-checked my user/pass combo.

Then I went to gmail to see if I could figure out if there was something with the account that was misconfigured. That's when I saw this email:

> Someone just used your password to try to sign in to your account from a non-Google app. Google blocked them, but you should check what happened. Review your account activity to make sure no one else has access.

To correct this issue, I had to open my Google account and confirm that yes, it was indeed me trying to log in. To solve the issue permanently, I had to go into my google account, look for the security settings, and then look for the setting for turning on access to less secure applications. Once I made this change, vmail successfully opened and listed my emails.

**Comment by sdondley** [comment]
Oh, so anyway, upshot is this should be documented somewhere if it isn't already.

**Comment by notalex** [comment]
@sdondley, thanks for reporting this. I will document this in the Readme. You may keep the 2 step auth with an app password as documented here: https://github.com/danchoi/vmail/wiki/How-to-use-vmail-with-2-step-protected-gmail-account
